### ISSUE TITLE
What are the limitations on aspose-tasks / Aspose.Tasks-for-.NET?

### ISSUE THREAD

**Issue by it19862** [aspose-tasks/Aspose.Tasks-for-.NET#38]
What are the limitations for the Aspose.Tasks-for-.NET?
Or is it not a demo?

**Comment by kashifiqb** [comment]
Aspose.Tasks API  is not free and imposes [evaluation limitations](https://docs.aspose.com/display/tasksnet/Licensing#Licensing-EvaluateAspose.Tasks) if you do not apply a license. You can get a 30-day temporary license free of cost in order to work with the API without evaluation limitations.
