### ISSUE TITLE
How to fix the error "does not exist in the current context."?

### ISSUE THREAD

**Issue by it19862** [aspose-tasks/Aspose.Tasks-for-.NET#39]
How to fix the error "does not exist in the current context."?

Uncommented unit
"// Articles"
Visual studio produces an error:
"The name" aligncellcontents "does not exist in the current context.
The name "changeganttbarscolorgradient" does not exist in the current context.
The name "implementcustombarstylewriting" does not exist in the current context.
The name "readcustombarstyle" does not exist in the current context.
The name "renderdifferentpresentationformatstoxaml" does not exist in the current context.
The name "renderganttchartwithbarsnotrolledup" does not exist in the current context.
The name "rendermultipagetiff" does not exist in the current context.
The name "renderprojecttopredefinedpagesizes" does not exist in the current context.
The name "rendertoxaml" does not exist in the current context.
The name "renderxamlwithoptions" does not exist in the current context.
The name "retrievetaskembeddeddocuments" does not exist in the current context.
The name "setganttchartviewstartdate" does not exist in the current context.
The name "sorttasksbycolumninganttchart" does not exist in the current context.

![3099](https://user-images.githubusercontent.com/18245828/35463695-fcc4b2c4-0302-11e8-8ca6-9e437cecff12.jpg)

**Comment by kashifiqb** [comment]
@it19862 ,

Just add the _using Aspose.Tasks.Examples.CSharp.Articles;_ at the top of this page to fix this issue. We have already fixed it and you can refresh your fork to get the changes included in your project. Let us know if you need any further assistance in this regard.
