### ISSUE TITLE
How to get a license?

### ISSUE THREAD

**Issue by it19862** [aspose-tasks/Aspose.Tasks-for-.NET#40]
How to get a license?

I send the request, but the letter does not come
![3100](https://user-images.githubusercontent.com/18245828/35469836-e08458f2-034e-11e8-8f42-dee34a3f5f42.jpg)

**Comment by kashifiqb** [comment]
@it19862 ,

If you don't get license, you can put a request for the same in [Aspose.Purchase forum](https://forum.aspose.com/c/purchase). Our team will get to you on this.
